PREDICTION_COLUMN = "prediction"
BM25_PREDICTION_COLUMN = "bm25_prediction"
LLM2VEC_PREDICTION_COLUMN = "llm2vec_prediction"
DATASET_QUERY_COLUMN = "query"
DATASET_POSITIVE_COLUMN = "positive"
DATASET_NEGATIVE_COLUMN = "negative"
DATASET_COLUMNS_FOR_TEXT = [
    DATASET_QUERY_COLUMN,
    DATASET_POSITIVE_COLUMN,
    DATASET_NEGATIVE_COLUMN,
]
HAS_POSITIVE_AND_NEGATIVE_EXAMPLE_COLUMN = "has_positive_and_negative"
STEMMER_LANGUAGE = "danish"